export { AuthAdapterService } from './auth';
export { CityAdapterService } from './city';
export { CommentAdapterService } from './comment';
export { FavoriteAdapterService } from './favorite';
export { HotelAdapterService } from './hotel';
export { RatingAdapterService } from './rating';
export { UserAdapterService } from './user';
export { UserTypeAdapterService } from './user-type';
export { CommonAdapterModule } from './common-adapter.module';
